#
# Copyright (c) 2021-2022 T-Systems International GmbH (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

################################################################
# Partial Configuration of the AAS Proxy for the Catena-X DEV042
################################################################

aasproxy:
  proxyHost: "sia-lb.telekom.de"
  proxyPort: 8080
  targetUrl: https://catenaxdev042akssrv.germanywestcentral.cloudapp.azure.com/semantics/
