#
# Copyright (c) 2021-2022 T-Systems International GmbH (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

###########################################################
# Configuration of the AAS Proxy
###########################################################

# Exposed Web Server (Incoming)
server:
  port: 4242
openapi:
  dotAASPart2HTTPRESTRegistryAndDiscovery:
    base-path:
# Delegatied Web Server (Outgoing)
aasproxy:
  noProxyHosts: localhost
